### PR TITLE
[CFD-11] Starter task 2 - Helena

### PR DESCRIPTION
**Pull request by helenaglow**
### Description

- [X] Created endpoints in packages/api/src/router/developer.ts:
-  `helenaglowacki_info` : returns info about me!
- `helenaglowacki_upvote` : increments upvote by 1
- [X] Created a component under apps/nextjs/src/components/developers/ called `helenaglowacki.tsx` that calls my endpoint and shows information about me. (_I like purple so it is purple_)
Screenshot 2023-10-21 at 6 41 22 PM

### Reason for Change

Completes CFD-11

### Type of change

- [X] New feature (non-breaking change which adds functionality) 

### Testing

Don't worry about it

### CODE REVIEW

**Review by BakerWJ — APPROVED** [review]
lgtm!

**Review by ganeshasapu — APPROVED** [review]
Nice work and styling + good song choice lol

**Comment by BakerWJ** [comment]
RIP forgot to mention in my review, but for PR descriiptions you should put the picture in the testing section. Basically the testing section is just "proof this works"

**Comment by helenaglow** [comment]
Ohhh I ok ok I will fix that

**Pull request merged**
