### PR TITLE
Leventozay2003/cfd 8 add name to readme levent

### PR DESCRIPTION
**Pull request by LevOzay**
### Description

Added my name to the Contributors under README

### Reason for Change

Completes CFD-8

### Type of change

- [X] Documentation update

### Testing

No tests

### CODE REVIEW

**Review by BakerWJ — APPROVED** [review]
not sure why the CI checks aren't running -- try closing and re-opening the PR or the top answer here https://stackoverflow.com/questions/52200096/github-pull-request-waiting-for-status-to-be-reported . It might also run properly when you make a new commit fixing the merge conflict.

**Comment by LevOzay** [comment]
> not sure why the CI checks aren't running -- try closing and re-opening the PR or the top answer here https://stackoverflow.com/questions/52200096/github-pull-request-waiting-for-status-to-be-reported . It might also run properly when you resolve the branch conflict

I did both but nothing seems to change

**Comment by BakerWJ** [comment]
Hmmm... can you try resolving the conflicts and see if the new commit refreshes the check?

**Comment by LevOzay** [comment]
Yeah I tried fixing it but at this point I don't know what's going on

**Pull request merged**
