### PR TITLE
[CFD-127] remove title from createpost endpiont

### PR DESCRIPTION
**Pull request by helenaglow**
### Description

Removed title from create post endpoint
### Reason for Change

Completes CFD-127
### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by helenaglow** [comment]
Should I also update `createpost.tsx`?

**Comment by BakerWJ** [comment]
😭 sorry I made a mistake with the ticket -- can you update the Discussion endpoint, not the Post endpoint?

**Comment by helenaglow** [comment]
Ok

**Comment by helenaglow** [comment]
Should now be updated

**Comment by BakerWJ** [comment]
can you rebase onto main -- it shouldn't show that any of the db-related files are modified 🤔

**Comment by helenaglow** [comment]
Omg true. I just blanked yea I'll do that when I get home.

**Comment by helenaglow** [comment]
Ya know I am just gonna delete and remake cause I think that will be easier. I don't have time to fix my mistakes

**Pull request closed without merging**
